version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: brainvault_backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/brainvault
    command: npm run dev
    volumes:
      - ./Backend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: brainvault_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
